# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('type', models.CharField(choices=[('1', 'dianzi'), ('2', 'shuji')], max_length=1, verbose_name='\u5546\u54c1\u7c7b\u578b')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('image', models.ImageField(default='pic_folder/None/no-image.jpg', upload_to='pic_folder', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('content', models.TextField(blank=True, verbose_name='\u5546\u54c1\u5185\u5bb9')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
