# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booke',
            new_name='Book',
        ),
    ]
